
[ERRO][20210619-19:38:23][modules.plugin.system.updater]Traceback (most recent call last):
  File "/Users/fuyifan/Documents/eink-clock/eink-clock-mP/modules/plugin/system/updater.py", line 12, in checkForUpdate
    raise Exception
Exception
